name: Compile Audiophile OTG APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Package APK into ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AudiophileOTG-compiled-apk
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 14
